### ISSUE TITLE
Pointer Version 1.0 Crash by right click to open with the pointer a chest

### ISSUE THREAD

**Issue by Titoo8899** [CleanroomMC/Pointer#1]
Hi,
I have your Mod Test and have in a World a chest with swort and blocks inside with sneak and rightclick save. Now have I with the pointer right click to open this chest in a little distance. And then have Crash the game. Please look the Crash report and I hope you can fix the Problem.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Fluidlogged API Plugin (Fluidlogged-API-v1.8.1c-mc1.12.2.jar)
  SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.2.jar)
Contact their authors BEFORE contacting forge

// My bad.

Time: 7/17/22 2:37 PM
Description: Unexpected error

java.lang.ClassCastException: net.minecraft.client.entity.EntityPlayerSP cannot be cast to com.cleanroommc.pointer.EntityPlayerExpansion
	at com.cleanroommc.pointer.ItemPointer.func_77659_a(ItemPointer.java:65)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1808)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.cleanroommc.pointer.ItemPointer.func_77659_a(ItemPointer.java:65)
	at net.minecraft.item.ItemStack.func_77957_a(ItemStack.java:217)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187101_a(PlayerControllerMP.java:511)
	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1597)
	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:2254)
	at net.minecraft.client.Minecraft.func_184118_az(Minecraft.java:2020)

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Titoo8899'/70, l='MpServer', x=-340.91, y=4.00, z=-110.00]]
	Chunk stats: MultiplayerChunkCache: 960, 960
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-258,4,-254), Chunk: (at 14,0,2 in -17,-16; contains blocks -272,0,-256 to -257,255,-241), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 113440 game time, 2551 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: true), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 25 total; [EntityPlayerSP['Titoo8899'/70, l='MpServer', x=-340.91, y=4.00, z=-110.00], EntityPainting['Painting'/43, l='MpServer', x=-286.03, y=2.50, z=-224.50], EntityVillager['Villager'/13, l='MpServer', x=-386.55, y=4.00, z=-177.92], EntityVillager['Villager'/14, l='MpServer', x=-387.95, y=5.00, z=-167.88], EntityVillager['Villager'/17, l='MpServer', x=-378.48, y=4.00, z=-181.44], EntityVillager['Villager'/18, l='MpServer', x=-361.50, y=4.00, z=-149.30], EntitySheep['Sheep'/27, l='MpServer', x=-317.75, y=4.00, z=-135.21], EntityArmorStand['Armor Stand'/34, l='MpServer', x=-288.50, y=1.00, z=-207.50], EntityArmorStand['Armor Stand'/35, l='MpServer', x=-290.50, y=1.00, z=-207.50], EntityArmorStand['Armor Stand'/36, l='MpServer', x=-292.50, y=1.00, z=-207.50], EntityArmorStand['Armor Stand'/37, l='MpServer', x=-294.50, y=1.00, z=-207.50], EntityArmorStand['Armor Stand'/38, l='MpServer', x=-296.50, y=1.00, z=-207.50], EntityChicken['Chicken'/39, l='MpServer', x=-294.45, y=4.00, z=-185.81], EntityChicken['Chicken'/40, l='MpServer', x=-288.45, y=4.00, z=-149.19], EntityPainting['Painting'/43, l='MpServer', x=-286.03, y=2.50, z=-224.50], EntityPainting['Painting'/44, l='MpServer', x=-286.03, y=2.50, z=-211.00], EntityPainting['Painting'/45, l='MpServer', x=-286.03, y=2.50, z=-222.00], EntityPainting['Painting'/46, l='MpServer', x=-286.03, y=3.00, z=-218.50], EntityArmorStand['Armor Stand'/47, l='MpServer', x=-286.50, y=1.00, z=-207.50], EntityItem['item.item.egg'/48, l='MpServer', x=-284.78, y=4.00, z=-140.92], EntityChicken['Chicken'/49, l='MpServer', x=-269.86, y=4.00, z=-138.68], EntityChicken['Chicken'/50, l='MpServer', x=-269.85, y=4.00, z=-138.13], EntityPainting['Painting'/44, l='MpServer', x=-286.03, y=2.50, z=-211.00], EntityPainting['Painting'/45, l='MpServer', x=-286.03, y=2.50, z=-222.00], EntityPainting['Painting'/46, l='MpServer', x=-286.03, y=3.00, z=-218.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:427)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4741783640 bytes (4522 MB) / 5368709120 bytes (5120 MB) up to 10737418240 bytes (10240 MB)
	JVM Flags: 8 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx10G -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2860 15 mods loaded, 15 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID              | Version        | Source                               | Signature                                |
	|:------ |:--------------- |:-------------- |:------------------------------------ |:---------------------------------------- |
	| LCHIJA | minecraft       | 1.12.2         | minecraft.jar                        | None                                     |
	| LCHIJA | mcp             | 9.42           | minecraft.jar                        | None                                     |
	| LCHIJA | FML             | 8.0.99.99      | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge           | 14.23.5.2860   | forge-1.12.2-14.23.5.2860.jar        | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | securitycraft   | v1.9.2         | [1.12.2]+SecurityCraft+v1.9.2.jar    | None                                     |
	| LCHIJA | test            | 1.0            | [1.12.2]Better+Flashlight-1.2.jar    | None                                     |
	| LCHIJA | airportlight    | [1.12.2]-2.3.3 | AirPort-[1.12.2]-2.3.3.jar           | None                                     |
	| LCHIJA | customnpcs      | 1.12           | CustomNPCs_1.12.2-(05Jul20).jar      | None                                     |
	| LCHIJA | fluidlogged_api | 1.8.1c         | Fluidlogged-API-v1.8.1c-mc1.12.2.jar | None                                     |
	| LCHIJA | invisiblelights | 1.0.53         | invisiblelights-1.0.53.jar           | None                                     |
	| LCHIJA | lottweaks       | 3.0.5          | LotTweaks-mc1.12.2-version-3.0.5.jar | None                                     |
	| LCHIJA | parkour         | 1.5            | parkour-1.5.jar                      | None                                     |
	| LCHIJA | pointer         | 1.0            | pointer-1.0.jar                      | None                                     |
	| LCHIJA | shifumimod      | 1.0            | ShifumiMod-1-3.jar                   | None                                     |
	| LCHIJA | soundcnpc       | 1.0.0          | soundcnpc1.12.2-1.0.jar              | None                                     |

	Loaded coremods (and transformers): 
Fluidlogged API Plugin (Fluidlogged-API-v1.8.1c-mc1.12.2.jar)
  git.jbredwards.fluidlogged_api.mod.asm.ASMHandler$Transformer
SecurityCraftLoadingPlugin ([1.12.2]+SecurityCraft+v1.9.2.jar)
  
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.6.0 NVIDIA 516.59' Renderer: 'NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2'
	Launched Version: 1.12.2-forge-14.23.5.2860
	LWJGL: 2.9.4
	OpenGL: NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 GL version 4.6.0 NVIDIA 516.59, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 6x Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz

**Comment by Titoo8899** [comment]
Little Info to the other Mods:
Parkour is the "Parkour and more" mod (Link: https://www.curseforge.com/minecraft/mc-mods/parkour-and-more)

**Comment by Titoo8899** [comment]
mixin forgot to make in modsfolder
